#!/bin/bash

DEG_INTERVAL=$1

module -q restore
module -q load cpe/21.09
module -q load PrgEnv-gnu

LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}

module -q load cray-hdf5
module -q load cray-netcdf
module -q load cray-fftw

WMAM_DATA_ROOT=${HOME/home/work}/tests/WMAM/shd/data

SHARED_UTILS=${HOME/home/work}/utils
GMT_ROOT=${SHARED_UTILS}/gmt/6.3.0
GD2GC_ROOT=${SHARED_UTILS}/gd2gc/1.0
PATH=${GD2GC_ROOT}/bin:${GMT_ROOT}/bin:${PATH}
LD_LIBRARY_PATH=${GMT_ROOT}/lib64:${LD_LIBRARY_PATH}

cat ${WMAM_DATA_ROOT}/wdmam.asc \
 | awk '{print $1,$2,$3}' \
 | gmt blockmedian -I$DEG_INTERVAL -R-180/180/-90/90 -C \
 > ./wdmam0p2_gdlo-gdla-dF.tmp
cat ./wdmam.asc \
 | awk '{print $1,$2,$4}' \
 | gmt blockmedian -I$DEG_INTERVAL -R-180/180/-90/90 -C \
 > ./wdmam0p2_gdlo-gdla-id.tmp

paste ./wdmam0p2_gdlo-gdla-id.tmp \
      ./wdmam0p2_gdlo-gdla-dF.tmp \
 | awk '{if ($1<180) {print $0}}' \
 | awk '{if ($2>-90 && $2<90) {print $0}}' \
 | awk 'BEGIN {height=-99999} \
        {if ($3>=11.5) {height=5.0} \
         else {height=0.0}; print $1,$2,height,$6}' \
 > wdmam_geodetic.tmp

cat wdmam_geodetic.tmp \
 | awk '{print 90.0-$2,$3,0,0}' \
 | gd2gc_cmdln \
 | tail -n+2 \
 | awk '{printf("%f %f\n",90.0-$6,$7)}' \
 > wdmam_geocentric.tmp

paste wdmam_geodetic.tmp wdmam_geocentric.tmp \
 | awk '{printf("%9.4f %8.4f %8.3f %10.4f\n",$1,$5,$6,$4)}' \
 > wdmam_geocentric.dat
